# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c19550dcfce88c99e822b7bc3181270cf2264464fb7ffd0662bef1e09b53feba802e55a309e10e58281910ba0e1504a77320f6ba40868eb41ff105761543be9

test:
  secret_key_base: e22867a16870af92e048259ea818799bbe05ff3d5c450cb64712246754fd33b6b1d71d1f783a52f5c0553906a947b19759f12e284ecbcbc694ad3421f514dfdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
